const text = [
  "I'm baby xOXO hell of banjo, iPhone kale chips cold-pressed paleo actually unicorn cray. Freegan kombucha vinyl, slow-carb coloring book blog franzen ugh. ",
  "Subway tile venmo quinoa leggings chartreuse butcher squid roof party organic thundercats. Waistcoat stumptown artisan jean shorts deep v taxidermy master cleanse lo-fi, edison bulb shoreditch. Intelligentsia franzen chambray, meditation small batch master cleanse taxidermy marfa pour-over unicorn enamel pin fashion axe",
  "Normcore church-key shaman shabby chic keytar pickled umami 90's kickstarter bespoke. Umami occupy direct trade edison bulb. 3 wolf moon food truck quinoa kickstarter kale chips. Seitan shabby chic 8-bit asymmetrical. Tofu kale chips craft beer taiyaki, sartorial raw denim man bun disrupt unicorn. Church-key echo park blue bottle fashion axe PBR&B. Pug typewriter migas, twee post-ironic whatever succulents letterpress.",
  "Tacos lumbersexual iPhone, hashtag wayfarers activated charcoal food truck farm-to-table kinfolk cold-pressed. Marfa meggings helvetica 90's bespoke schlitz tacos. Intelligentsia blue bottle bicycle rights kickstarter irony biodiesel retro. Gluten-free air plant skateboard irony, keffiyeh yuccie master cleanse hella copper mug. Yr meditation ugh skateboard hashtag venmo hot chicken",
  "Venmo locavore letterpress synth kickstarter cred flexitarian tousled drinking vinegar activated charcoal semiotics yuccie. Pabst cardigan fingerstache aesthetic banh mi kale chips shabby chic activated charcoal paleo bitters disrupt tofu coloring book adaptogen shaman. Irony williamsburg flexitarian tilde PBR&B master cleanse. Readymade DIY twee, kitsch banjo taiyaki palo santo bushwick vegan YOLO. Pop-up tattooed kitsch bicycle rights.",
  "Bitters trust fund air plant, palo santo PBR&B cornhole flexitarian meh keffiyeh squid tilde whatever literally. Pok pok squid forage distillery vegan gastropub kale chips farm-to-table messenger bag vice cornhole craft beer. Neutra retro mumblecore wolf. Messenger bag authentic tofu kogi umami marfa kickstarter lomo. Crucifix gastropub artisan schlitz organic.",
  "Tacos lumbersexual iPhone, hashtag wayfarers activated charcoal food truck farm-to-table kinfolk cold-pressed. Marfa meggings helvetica 90's bespoke schlitz tacos. Intelligentsia blue bottle bicycle rights kickstarter irony biodiesel retro. Gluten-free air plant skateboard irony, keffiyeh yuccie master cleanse hella copper mug. Yr meditation ugh skateboard hashtag venmo hot chicken ethical man bun cray flexitarian. Adaptogen schlitz squid forage cred. Direct trade mumblecore celiac ethical occupy.",
  "I'm baby xOXO hell of banjo, iPhone kale chips cold-pressed paleo actually unicorn cray. Freegan kombucha vinyl, slow-carb coloring book blog franzen ugh. Subway tile venmo quinoa leggings chartreuse butcher squid roof party organic thundercats. Waistcoat stumptown artisan jean shorts deep v taxidermy master cleanse lo-fi, edison bulb shoreditch. Intelligentsia franzen chambray, meditation small batch master cleanse taxidermy marfa pour-over unicorn enamel pin fashion axe. Pinterest etsy lomo tattooed listicle. Subway tile YOLO tbh before they sold out, thundercats cliche echo park vinyl tumeric keffiyeh banjo cloud bread mlkshk.",
  "Bitters trust fund air plant, palo santo PBR&B cornhole flexitarian meh keffiyeh squid tilde whatever literally. Pok pok squid forage distillery vegan gastropub kale chips farm-to-table messenger bag vice cornhole craft beer. Neutra retro mumblecore wolf. Messenger bag authentic tofu kogi umami marfa kickstarter lomo. Crucifix gastropub artisan schlitz organic.",
];
export default text;
